#!/bin/bash

config-pin P8.7 gpio_pd
config-pin P8.9 gpio_pd
config-pin P8.15 gpio_pd
config-pin P8.17 gpio_pd
config-pin P8.27 gpio_pd
config-pin P8.29 gpio_pd
config-pin P8.31 gpio_pd
config-pin P8.33 gpio_pd
config-pin P8.35 gpio_pd
config-pin P8.37 gpio_pd
config-pin P8.39 gpio_pd
config-pin P8.41 gpio_pd

echo 8 > /sys/class/gpio/export
echo 9 > /sys/class/gpio/export
echo 10 > /sys/class/gpio/export
echo 27 > /sys/class/gpio/export
echo 47 > /sys/class/gpio/export
echo 66 > /sys/class/gpio/export
echo 69 > /sys/class/gpio/export
echo 74 > /sys/class/gpio/export
echo 76 > /sys/class/gpio/export
echo 78 > /sys/class/gpio/export
echo 86 > /sys/class/gpio/export
echo 87 > /sys/class/gpio/export
