FLAGS = -Wall -lm

button_led_test: button_led_test.c
	gcc $(FLAGS) button_led_test.c -o button_led_test
	
compass_test: compass_test.c
	gcc $(FLAGS) compass_test.c -o compass_test
	
drivetest:	drivetest.c
	gcc $(FLAGS) drivetest.c -o drivetest
	
imu_test: imu_test.c
	gcc $(FLAGS) imu_test.c -o imu_test
	
IR_sensors_test: IR_sensors_test.c
	gcc $(FLAGS) IR_sensors_test.c -o IR_sensors_test
	
mecanum: mecanum.c
	gcc $(FLAGS) mecanum.c -o mecanum
	
motor_test: motor_test.c
	gcc $(FLAGS) motor_test.c -o motor_test
	
prox_adc_test: prox_adc_test.c
	gcc $(FLAGS) prox_adc_test.c -o prox_adc_test
	
stage1_test: stage1_test.c
	gcc $(FLAGS) stage1_test.c -o stage1_test
	
test_nav: test_nav.c
	gcc $(FLAGS) test_nav.c -o test_nav
	
test_navsmart: test_navsmart.c
	gcc $(FLAGS) test_navsmart.c -o test_navsmart
